### ISSUE TITLE
Research testing frameworks and methods

### ISSUE THREAD

**Issue by njallskarp** [njallskarp/icelandic-qa-finetune#3]
Research best ways to test functions (which unit testing libraries), which integration tests and which end2end tests to run.

Once you're done, create a ticket in here for setting up the relevant testing libraries you found in your research.

**Comment by Eysteinn-Orn** [comment]
# For generic unit testing:
Here are some good options:

1. Pytest
2. Unittest
3. Nose2

But I think Pytest is best here because, even though it is mainly used for unit tests, it's very flexible and powerful to also be used for integration tests and end-to-end tests. It also has a lot of plugins available.

Unittest is simple and built in python already, so there is not a lot of overhead for that but lacks the robustness? that pytest has.

Nose2 extends Unittest to provide more make testing nicer and more human readable but it's documentation also recommends Pytest.

# For ML testing
Options:

1. torch.testing (built in testing from pytorch)
2. MLtest
3. torchtest

There already is a built in testing library in pytorch that provides some basic tests for ML models. But I also think it might be worth considering MLtest since it is robust and has PyTorch support but it might take some time to integrate into our workflow. It looks like it is for computer vision mainly but I think it also provides generic ML model testing.

MLtest might be a lot of work and requires to get into contact with the team that develops that solution since we would be applying for early access.

torchtest is some free and open source testing library from 4 years ago that is pretty simple.

Overall the best solution for our purposes would be the built in option, or maybe Njáll has some better ideas.

# For integration and end-to-end tests

either pytest or possibly behave?

behave is a python behaviour driven development framework that has human readable tests that define system behaviour and is excellent for high level end-to-end tests.

pytest is also a good candidate since we could be using it also for unit tests and can provide more.
